### ISSUE TITLE
Add Sinatra support

### ISSUE THREAD

**Issue by cbetta** [pixielabs/letsencrypt-rails-heroku#14]
I love this gem and would love to add it to a Sinatra app as well. Is there any reason this is Rails specific? It seems to me like we could plug a similar middleware into Sinatra with little issue.

Would this be possible within this gem or easier to achieve with a new gem?

**Comment by jalada** [comment]
I haven't tried but you should be able to use the gem as is with Sinatra. You'd need to:

1. Call `Letsencrypt.configure` (like the Railtie)
2. Insert the `Letsencrypt::Middleware` middleware the same way you insert other Rack middleware.

**Comment by cbetta** [comment]
@jalada tnx, giving this a try now. Will document what I did

**Comment by cbetta** [comment]
@jalada currently getting stuck on:

```sh
** Invoke letsencrypt:renew (first_time)
rake aborted!
Don't know how to build task 'environment' (see --tasks)
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task_manager.rb:71:in `[]'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:61:in `lookup_prerequisite'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:57:in `block in prerequisite_tasks'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:57:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:57:in `prerequisite_tasks'

/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:207:in `invoke_prerequisites'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => letsencrypt:renew
```

Which seems to refer to https://github.com/pixielabs/letsencrypt-rails-heroku/blob/master/lib/tasks/letsencrypt.rake#L9. What shall we do with this? Wondering if the `=> :environment` statement is even needed.
