### ISSUE TITLE
Excon::Error:NotFound (404) during config_var updates to app

### ISSUE THREAD

**Issue by jegodwin** [pixielabs/letsencrypt-rails-heroku#24]
I'm getting the following stack trace when running the `renew` rake task:

```
Running rake letsencrypt:renew on ⬢ my-heroku-app-name... up, run.8227 (Hobby)
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
Creating account key...Done!
Registering with LetsEncrypt...Done!
Performing verification for staging.jomoapp.com:
Setting config vars on Heroku...rake aborted!
Excon::Error::NotFound: Expected([200, 201, 202, 204, 206, 304]) <=> Actual(404 Not Found)
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.54.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.54.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.54.0/lib/excon/connection.rb:388:in `response'
/app/vendor/bundle/ruby/2.4.0/gems/excon-0.54.0/lib/excon/connection.rb:252:in `request'
/app/vendor/bundle/ruby/2.4.0/gems/heroics-0.0.17/lib/heroics/link.rb:111:in `request_with_cache'
/app/vendor/bundle/ruby/2.4.0/gems/heroics-0.0.17/lib/heroics/link.rb:66:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/heroics-0.0.17/lib/heroics/resource.rb:28:in `method_missing'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/platform-api-45ddb3c1a7e2/lib/platform-api/client.rb:1104:in `update'
/app/vendor/bundle/ruby/2.4.0/gems/letsencrypt-rails-heroku-0.3.0/lib/tasks/letsencrypt.rake:39:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/letsencrypt-rails-heroku-0.3.0/lib/tasks/letsencrypt.rake:32:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/letsencrypt-rails-heroku-0.3.0/lib/tasks/letsencrypt.rake:32:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => letsencrypt:renew
```

Is there something simple that I'm missing here? It's failing on this block of code:
```
heroku.config_var.update(heroku_app, {
    'ACME_CHALLENGE_FILENAME' => challenge.filename,
    'ACME_CHALLENGE_FILE_CONTENT' => challenge.file_content
})
```

**Comment by Enfop** [comment]
Hi 

not sure if it helps but i got the same error when i misstyped the app name in the 
HEROKU_APP Enviroment Variable.

**Comment by jalada** [comment]
As per @Enfop, have you got all your environment variables set as per the README?

**Comment by jegodwin** [comment]
Yeah, I've had these setup since day one; no spelling errors.
![screen shot 2017-02-01 at 1 29 45 pm](https://cloud.githubusercontent.com/assets/2034140/22520620/0bf76d0e-e883-11e6-86cd-c87207625757.png)

**Comment by nerdi** [comment]
I have the same issue as jegodwin.
Am hoping there is a solution here.
My config variables are definitely as per readme.

**Comment by tgmerritt** [comment]
@jegodwin 

Your stack trace references line 1104 in client.rb in the platform-api library.

```
# Update config-vars for app. You can update existing config-vars by setting them again, and remove by setting it to `null`.
    #
    # @param app_id_or_app_name: unique identifier of app or unique name of app
    # @param body: the object to pass as the request payload
    def update(app_id_or_app_name, body = {})
      @client.config_var.update(app_id_or_app_name, body)
    end
```

It definitely appears that your HEROKU_APP value isn't the name of your app, misspelled, something...

Please definitely check the values - I see the screenshot that you've submitted that shows the KEYS you've configured, what is the HEROKU_APP value?

**Comment by jalada** [comment]
@jegodwin did you ever get this sorted?

**Comment by jegodwin** [comment]
I apologize, I somehow missed @tgmerritt's response. After looking at this just now, it looks as though he is right; my `HEROKU_APP` value has an `_` instead of the `-` that it should have. I haven't tested this yet since I found a work around for the issue, but I think it's safe to close this issue.

Thanks for reminder @jalada, and thank you @tgmerritt for pointing out my issue.
