### ISSUE TITLE
403 Forbidden on Adding Cert

### ISSUE THREAD

**Issue by coreyward** [pixielabs/letsencrypt-rails-heroku#8]
Getting the following when running `letsencrypt:renew` for the first time on a new app:

```
Adding new certificate...rake aborted!
Excon::Error::Forbidden: Expected([200, 201, 202, 204, 206, 304]) <=> Actual(403 Forbidden)
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/connection.rb:388:in `response'
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/connection.rb:252:in `request'
/app/vendor/bundle/ruby/2.3.0/gems/heroics-0.0.17/lib/heroics/link.rb:111:in `request_with_cache'
/app/vendor/bundle/ruby/2.3.0/gems/heroics-0.0.17/lib/heroics/link.rb:66:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/heroics-0.0.17/lib/heroics/resource.rb:28:in `method_missing'
/app/vendor/bundle/ruby/2.3.0/bundler/gems/platform-api-45ddb3c1a7e2/lib/platform-api/client.rb:2446:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/letsencrypt-rails-heroku-0.2.7/lib/tasks/letsencrypt.rake:102:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => letsencrypt:renew
```

**Comment by originalpete** [comment]
Hey @coreyward, can you please re-run the rake task with --trace?

**Comment by coreyward** [comment]
Sure:

```
Adding new certificate...rake aborted!
Excon::Error::Forbidden: Expected([200, 201, 202, 204, 206, 304]) <=> Actual(403 Forbidden)
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/middlewares/expects.rb:7:in `response_call'
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/middlewares/response_parser.rb:9:in `response_call'
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/connection.rb:388:in `response'
/app/vendor/bundle/ruby/2.3.0/gems/excon-0.53.0/lib/excon/connection.rb:252:in `request'
/app/vendor/bundle/ruby/2.3.0/gems/heroics-0.0.17/lib/heroics/link.rb:111:in `request_with_cache'
/app/vendor/bundle/ruby/2.3.0/gems/heroics-0.0.17/lib/heroics/link.rb:66:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/heroics-0.0.17/lib/heroics/resource.rb:28:in `method_missing'
/app/vendor/bundle/ruby/2.3.0/bundler/gems/platform-api-45ddb3c1a7e2/lib/platform-api/client.rb:2446:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/letsencrypt-rails-heroku-0.2.7/lib/tasks/letsencrypt.rake:102:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `load'
/app/vendor/bundle/ruby/2.3.0/bin/rake:23:in `<main>'
Tasks: TOP => letsencrypt:renew
```

**Comment by coreyward** [comment]
I figured out what caused the issue: the account I oAuth'ed from was on the team with `member` access. Apparently `admin` access is needed in order to add the SSL certs.

I guess I should have known from the 403, but I of course started looking at more complicated possibilities.  ¯\_(ツ)_/¯
